export const FIELDS = [
  { title: "Fiction", value: "fiction" },
  { title: "Mystery & Thriller", value: "myt" },
  { title: "Historial Fiction", value: "historical" },
  { title: "Fantasy", value: "fantasy" },
  { title: "Romance", value: "romance" },
  { title: "Science Fiction", value: "scifi" },
  { title: "Horror", value: "horror" },
  { title: "Humor", value: "humor" },
  { title: "Nonfiction", value: "nonfiction" },
  { title: "Memoir & Autobiography", value: "mya" },
  { title: "History & Biography", value: "hyb" },
  { title: "Science & Technology", value: "syt" },
  { title: "Food & Cookbooks", value: "fyc" },
  { title: "Graphic Novels & Comics", value: "gyc" },
  { title: "Poetry", value: "poetry" },
  { title: "Debut Novel", value: "debut" },
  { title: "Young Adult Fiction", value: "youngfic" },
  { title: "Young Adult Fantasy", value: "youngfan" },
  { title: "Middle Grade & Children's", value: "myc" },
  { title: "Picture Books", value: "picture" },
];
